# action.yml
name: 'ZAT Tools'
description: 'Run the ZAT Tools'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subdomain }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.app-id }}
