# action.yml
name: 'ZAT Tools'
description: 'Run the ZAT Tools'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.subdomain }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.app-id }}
