# action.yml
name: 'Zendesk App Tools - Update App'
description: 'Update an existing app in a Zendesk instance. Requires a .zat file/'
branding:
  icon: 'arrow-up-circle'  
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
